import os


rule bin_files:
    input:
        fastq = os.path.join(config["input_path"], "{barcode}", f"fastq_runid_{config['run_id']}_0.fastq")
    params:
        file_path = os.path.join(config["input_path"], "{barcode}")
    output:
        binned = os.path.join(config["output_path"],"binned","{barcode}.fastq")
    shell:
        """
        cat {params.file_path}/fastq_*.fastq > {output[0]}
        """

rule kraken_classify:
    input:
        db=config["kraken_db"],
        binned=os.path.join(config["output_path"],"binned","{barcode}.fastq"),
        taxonomy="/localdisk/home/s1680070/seawater_wimp/kraken_data/ADE_working/classified/taxonomy.tab"
    output:
        kraken=config["output_path"] + "/classified/kraken_output/{barcode}.kraken",
    params:
        barcode="{barcode}",
        outdir=config["output_path"] + "/classified/kraken_reports/{barcode}",
        classified=config["output_path"] + "/classified"
    threads:
        2
    shell:
        """
        mkdir -p {params.outdir}
        kraken2 --db {input.db} \
            --report {params.outdir}/{params.barcode}.kreport2 \
            --classified-out {params.outdir}/{params.barcode}.fastq \
            --memory-mapping \
            {input.binned} \
            > {output.kraken};
        cat {output.kraken} >> {params.outdir}/{params.barcode}.kraken;
        ktImportTaxonomy \
            -q 2 -t 3 {params.classified}/*/*.kraken \
            -o {params.classified}/all_krona.html \
            &> {params.classified}/krona.log
        """