import os
from Bio import SeqIO
from adecoi.utils import histograms

print(config)

rule all:
    input:
        expand(os.path.join(config["output_path"],"classified","kraken_output","{barcode}.kraken"), barcode=config["barcodes"]),
        expand(os.path.join(config["output_path"],"filtered","{barcode}.fastq"), barcode=config["barcodes"]),
        expand(os.path.join(config["output_path"],"classified","krona_output","{barcode}.html"), barcode=config["barcodes"])


rule bin_files:
    input:
        fastq = os.path.join(config["input_path"], "{barcode}", f"fastq_runid_{config['runid']}_0.fastq")
    params:
        file_path = os.path.join(config["input_path"], "{barcode}")
    output:
        binned = os.path.join(config["output_path"],"binned","{barcode}.fastq")
    shell:
        """
        cat {params.file_path}/fastq_*.fastq > {output[0]}
        """

rule kraken_classify:
    input:
        db=config["kraken_db"],
        binned=os.path.join(config["output_path"],"binned","{barcode}.fastq"),
        taxonomy="/localdisk/home/s1680070/seawater_wimp/kraken_data/ADE_working/classified/taxonomy.tab"
    output:
        kraken=os.path.join(config["output_path"],"classified","kraken_output","{barcode}.kraken"),
        classified_out = os.path.join(config["output_path"],"classified","reads","{barcode}.fastq"),
        report = os.path.join(config["output_path"],"classified","reads","{barcode}.kreport2")
    params:
        barcode="{barcode}",
        classified=os.path.join(config["output_path"],"classified")
    threads:
        2
    shell:
        """
        kraken2 --db {input.db} \
            --report {output.report} \
            --classified-out {output.classified_out} \
            --memory-mapping \
            {input.binned} \
            > {output.kraken}
        """

rule make_krona:
    input:
        kraken=os.path.join(config["output_path"],"classified","kraken_output","{barcode}.kraken")
    output:
        krona=os.path.join(config["output_path"],"classified","krona_output","{barcode}.html")
    log: os.path.join(config["output_path"],"classified","krona_output","{barcode}.log")
    shell:
        """
        ktImportTaxonomy \
            -q 2 -t 3 {input.kraken} \
            -o {output.krona} \
            &> {log} 
        """

rule filter_by_length:
    input:
        os.path.join(config["output_path"],"binned","{barcode}.fastq")
    output:
        reads = os.path.join(config["output_path"],"filtered","{barcode}.fastq"),
        histogram1 = os.path.join(config["output_path"],"figures","{barcode}.unfiltered.svg"),
        histogram2 = os.path.join(config["output_path"],"figures","{barcode}.length_filtered.svg")
    run:
        fastq_records = []
        lengths = []
        filtered_lengths = []
        with open(output.reads,"w") as fw:
            for record in SeqIO.parse(input[0],"fastq"):
                length = len(record)
                lengths.append(length)
                if length > int(config["min_length"]) and length < int(config["max_length"]):
                    fastq_records.append(record)
                    filtered_lengths.append(length)
            SeqIO.write(fastq_records,fw, "fastq")
        histograms.make_read_length_histogram_svg(lengths,config["min_length"],config["max_length"], output.histogram1)
        histograms.make_read_length_histogram_svg(filtered_lengths,config["min_length"],config["max_length"], output.histogram2)

